services:
  postgres:
    container_name: postgres-sql-tms
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: task_manager
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
    
  mail-dev:
    container_name: mail-dev-tms
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo
  
  keycloak:
    container_name: keycloak-tms
    image: quay.io/keycloak/keycloak:24.0.3
    command:
      - "start-dev"
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
      
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local